### ISSUE TITLE
CNAME file is removed

### ISSUE THREAD

**Issue by jasperjorna** [BryanSchuetz/jekyll-deploy-gh-pages#12]
Hi there,

I'm running into the issue that when the build is pushed back to the `gh-pages` branch, the CNAME file is no longer present and therefore the site is no longer accesible. Is it possible to whitelist files to keep or something like that?

**Comment by BryanSchuetz** [comment]
Are you excluding the CNAME file in your `_config.yml` or .gitignore files? Not sure why else CNAME wouldn't get pushed. Happy to take a look at the repo if you send a link.

**Comment by thinkyhead** [comment]
What is the symptom of a missing `CNAME` file? We saw a 404 error when publishing our site using this action, and it turned out that, yep, `CNAME` was listed as an `exclude:` item in `_config.yml`.

Once we removed `CNAME` from the `exclude:` list (and made sure `destination: ./build` was set and that Ruby 2.4.4 was activated…) the publish went through perfectly!
